global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'django'
    static_configs:
      - targets: [ 'web:8000', 'web-2:8000', 'web-3:8000' ]
